### ISSUE TITLE
Support confirmation prompt at the end of the Wizard Flow

### ISSUE THREAD

**Issue by SethY8s** [aptos-labs/create-aptos-dapp#15]
Add a confirmation prompt at the end of the wizard that allows users to change their inputs before building the project. 

Example:
```shell

Project name: 'fakeName',
Choose how to start: 'Toollist Dapp',
Choose network: 'Devnet',
Choose your package manager: 'npm',

Do you wish to change anything? Yes | No. 

What do you wish to edit? "ProjectName" | "Start" | "Network" | "packageManager"

``` 

Hey @0xmaayan I will lay out exactly how I plan on implementing this in a few hours after my work and you can check it out before I actually add it to the codebase.

One thing before I start, how do I test this locally? I am unfamiliar with these terminal prompts and the readme only explains how to run the deployed npm prompt.

**Comment by 0xmaayan** [comment]
@SethY8s sounds good! 

You can check out the [CONTRIBUTING](https://github.com/aptos-labs/create-aptos-dapp/blob/main/CONTRIBUTING.md) file. Basically clone the repo, install dependencies and `pnpm run dev` from the root folder, that would start the wizard locally (might be a bit slow so give it a second =) ). You would need to run `pnpm run dev` after every code change

**Comment by 0xmaayan** [comment]
Solved with https://github.com/aptos-labs/create-aptos-dapp/pull/16

**Comment by SethY8s** [comment]
Hey @0xmaayan I just saw that Aptos was hiring for a full-stack developer. Looking at the credentials it looks like I have all the requirements and skills except I only have 3 years of experience and Aptos requires 5. Do you think it would be worth it for me to still apply? I love Web3 and really would like to help Aptos out more if possible. 

Sorry for replying on GitHub. I checked your profile and was hoping for an email or LinkedIn but couldn't find anything.  Hope you understand and thanks in advance!

**Comment by 0xmaayan** [comment]
> Hey @0xmaayan I just saw that Aptos was hiring for a full-stack developer. Looking at the credentials it looks like I have all the requirements and skills except I only have 3 years of experience and Aptos requires 5. Do you think it would be worth it for me to still apply? I love Web3 and really would like to help Aptos out more if possible.
> 
> Sorry for replying on GitHub. I checked your profile and was hoping for an email or LinkedIn but couldn't find anything. Hope you understand and thanks in advance!

Just messaged you on Linkedin!
