### ISSUE TITLE
npm run move:init Command Failure on Windows

### ISSUE THREAD

**Issue by mdmudassir0143** [aptos-labs/create-aptos-dapp#17]
When attempting to run the npm run move:init command in the my-aptos-dapp directory following the setup instructions, an error occurs related to the export command. This error prevents the initialization process for the CLI Profile.
![Screenshot 2023-12-22 215504](https://github.com/aptos-labs/create-aptos-dapp/assets/67314024/ea92e225-0bb4-428f-b07c-7aac841eb643)
Observe the error: 'export' is not recognized as an internal or external command, operable program or batch file.

**Comment by 0xmaayan** [comment]
should be resolved in latest version
