### ISSUE TITLE
npx stuck at "Installing the dependencies..."

### ISSUE THREAD

**Issue by enriquephl** [aptos-labs/create-aptos-dapp#214]
Force quit the initiation process and do `npm install` or 	`yarn install` to manually install the dependencies can fix.
No idea why this happened.

**Comment by 0xmaayan** [comment]
Hi @enriquephl , we experienced the same issue yesterday and it seems like it is related to the aptos-ts-sdk dependency. While we investigate the issue on the SDK side, we can solve it on the create-aptos-dapp project by changing the dependency version to
```
"@aptos-labs/ts-sdk": "^1.26.0",
```
note the `^` added to the version number.

After that, you should be able to run `npm install`. Remember to delete `node_modules` and `package-lock` before re installing the dependencies.
