### ISSUE TITLE
List a package manager as a prereq and exit the flow if yarn/npm/pnpm fails

### ISSUE THREAD

**Issue by heliuchuan** [aptos-labs/create-aptos-dapp#8]
The wizard chugs on and tells you `Success! You're ready to start building your dapp on Aptos.`

Update the readme to say that you need a package manager installed

The wizard should exit with an error.

<img width="861" alt="Screenshot 2023-09-21 at 11 07 33 AM" src="https://github.com/aptos-labs/create-aptos-dapp/assets/4912445/286821f8-55af-40a2-9795-05b16e55ecd5">

**Comment by 0xmaayan** [comment]
currently only `npm` is supported
